### ISSUE TITLE
如何联系

### ISSUE THREAD

**Issue by Cwhaxixi** [LightInk2020/NetworkDisk#1]
你好，我们有个项目想使用qt做网盘，但是业务还是有一些区别，我的qq9183005，有没有兴趣开发我们这个项目

**Comment by yuecao0119** [comment]
抱歉哈，最近在忙，可能没有时间



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年03月17日 10:12 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [LightInk2020/NetworkDisk] 如何联系 (Issue #1) |

你好，我们有个项目想使用qt做网盘，但是业务还是有一些区别，我的qq9183005，有没有兴趣开发我们这个项目
