### ISSUE TITLE
打不开notion

### ISSUE THREAD

**Issue by yangxiaoxuan127** [LightInk2020/NetworkDisk#2]
不知为何打不开您的notion，目前在学习QT，请问能否得到您总结的项目笔记。邮箱是yangxiaoxuan127@163.com
感谢

**Comment by yuecao0119** [comment]
notion是国外的笔记，你可以考虑一下翻墙再打开



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年04月04日 22:01 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [YueCao0119/NetworkDisk] 打不开notion (Issue #2) |

***@***.***
感谢

**Comment by yangxiaoxuan127** [comment]
不好意思 我就在国外，打开之后需要登陆，登陆后也不跳转，不知道是什么原因呢

**Comment by yuecao0119** [comment]
哦哦，好的，我明天起床看一下



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年04月04日 23:07 |
| 收件人 | ***@***.***> |
| 抄送至 | Yue ***@***.***>***@***.***> |
| 主题 | Re: [YueCao0119/NetworkDisk] 打不开notion (Issue #2) |

不好意思 我就在国外，打开之后需要登陆，登陆后也不跳转，不知道是什么原因呢

**Comment by yangxiaoxuan127** [comment]
不好意思，今天又尝试打开您的notion，显示“ you do not have access to VirMoon‘s Notion.Please contact an admin to add you as a member.” 如果可以的话请问能重新分享一下吗.万分感谢.

**Comment by yuecao0119** [comment]
不好意思，前几天太忙忘记了。现在已经修复问题了，同时在项目文件目录下我上传了笔记的markdown格式，希望可以给你提供帮助

**Comment by yangxiaoxuan127** [comment]
感谢。祝健康顺利。
