### ISSUE TITLE
这个项目是在Windows系统下编写的吗

### ISSUE THREAD

**Issue by LZNJUPT** [LightInk2020/NetworkDisk#5]

**Comment by yuecao0119** [comment]
是的



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年05月12日 20:54 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [yuecao0119/NetworkDisk] 这个项目是在Windows系统下编写的吗 (Issue #5) |

**Comment by LZNJUPT** [comment]
好的，感谢

Yue Cao ***@***.***> 于2024年5月12日周日 23:30写道：
